name: Automated Updates

on:
    schedule:
        # https://crontab.guru/every-7-days
        -   cron: "0 0 * * 0"

jobs:
    automated_updates:
        runs-on: ubuntu-latest

        name: "Regenerate Stats"

        steps:
            -   uses: actions/checkout@v2
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            -   uses: "ramsey/composer-install@v1"

            -   run: bin/console generate-stats --ansi
                env:
                     GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

            # see https://github.com/peter-evans/create-pull-request
            -
                name: Create pull-request
                uses: peter-evans/create-pull-request@v3
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    title: "Regenerate Stats"
                    commit-message: "Regenerate Stats"
                    base: "main"
                    delete-branch: true
                    author: "kaizen-ci <info@kaizen-ci.org>"
                    committer: "kaizen-ci <info@kaizen-ci.org>"
